name: Vinted Alert

# GitHub Actions déclenché toutes les 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  run-vinted-bot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 flask

      # 4️⃣ Exécuter le script
      - name: Run Vinted Bot
        env:
          VINTED_URL: ${{ secrets.VINTED_URL }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python main.py
